routes/web.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index');

Route::group(['prefix' => 'reportes'], function() {
    Route::get('/productos', 'Reports\ProductController@report');
    Route::get('/compras', 'Reports\PurchaseDocumentController@report');
    Route::get('/ventas', 'Reports\SaleDocumentController@report');
    Route::get('/vendedores', 'Reports\SellerController@report');
});

app/Models/Product.php
<?php

namespace App\Models;

use App\Scopes\CurrentBranchScope;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Product
 * @package App\Models
 *
 * @property integer id
 * @property integer branch_id
 * @property string code
 * @property string category
 * @property string brand
 * @property string laboratory
 * @property string measure_unit
 * @property string name
 * @property string composition
 * @property string description
 * @property string unit_price
 * @property string purchased_units
 * @property string sold_units
 */
class Product extends Model
{
    protected $fillable = [
        'branch_id', 'code', 'category', 'brand', 'laboratory',
        'measure_unit', 'name', 'composition', 'description',
        'unit_price', 'purchased_units', 'sold_units'
    ];

    protected $hidden = ['branch_id', 'created_at', 'updated_at'];

    protected static function boot()
    {
        parent::boot();
        static::addGlobalScope(new CurrentBranchScope());
    }

    public function setCategoryAttribute($value)
    {
        $category = Category::firstOrCreate([
            'name' => strtoupper($value)
        ]);
        $this->attributes['category'] = $category->name;
    }

    public function setBrandAttribute($value)
    {
        $brand = Brand::firstOrCreate([
            'name' => strtoupper($value)
        ]);
        $this->attributes['brand'] = $brand->name;
    }

    public function setLaboratoryAttribute($value)
    {
        $laboratory = Laboratory::firstOrCreate([
            'name' => strtoupper($value)
        ]);
        $this->attributes['laboratory'] = $laboratory->name;
    }

    public function setMeasureUnitAttribute($value)
    {
        $measure_unit = MeasureUnit::firstOrCreate([
            'name' => strtoupper($value)
        ]);
        $this->attributes['measure_unit'] = $measure_unit->name;
    }

    public function setCodeAttribute($value)
    {
        $this->attributes['code'] = strtoupper($value);
    }

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtoupper($value);
    }

    public function setCompositionAttribute($value)
    {
        $this->attributes['composition'] = strtoupper($value);
    }

    public function setDescriptionAttribute($value)
    {
        $this->attributes['description'] = strtoupper($value);
    }

    public function getInStockAttribute()
    {
        return $this->purchased_units - $this->sold_units;
    }
}

resources/views/pdf/generalpurchases.blade.php
@extends('layouts.pdf')

@section('content')
    <center>
        <h2 class="title has-text-dark is-size-4">{{$title}}</h2>
        <h5 class="subtitle is-size-6">DESDE: {{ date_format($from, 'd/m/Y') }} HASTA: {{ date_format($to, 'd/m/Y') }}</h5>
    </center>
    <div class="columns has-margin-top-5">
        <div class="column is-12">
            <table class="table is-fullwidth">
                <tr>
                    <th><center class="is-size-6">FECHA DE IMPRESIÓN: {{ date('d/m/Y') }}</center></th>
                    <th><center class="is-size-6">HORA DE IMPRESIÓN: {{ date('h:i:s a') }}</center></th>
                </tr>
            </table>
        </div>
    </div>
    <div class="columns has-margin-top-0">
        <div class="column is-12">
            <table class="table is-bordered is-striped is-narrow is hoverable is-fullwidth">
                <thead>
                <tr>
                    <th class="is-size-7" style="width: 5%">DÍA</th>
                    <th class="is-size-7" style="width: 20%">DOCUMENTO</th>
                    <th class="is-size-7" style="width: 45%">PROVEEDOR</th>
                    <th class="is-size-7" style="width: 10%">TOTAL</th>
                </tr>
                </thead>
                <thead>
                    @foreach($purchases as $purchase)
                        <tr>
                            <td class="is-size-7">{{ date_format($purchase->created_at, 'd') }}</td>
                            <td class="is-size-7">{{ $purchase->code }}</td>
                            <td class="is-size-7">{{ $purchase->provider_name }}</td>
                            <td class="is-size-7">{{ $purchase->total }}</td>
                        </tr>
                    @endforeach
                </thead>
            </table>
        </div>
    </div>
@endsection

resources/views/pdf/generalsales.blade.php
@extends('layouts.pdf')

@section('content')
    <center>
        <h2 class="title has-text-dark is-size-4">{{$title}}</h2>
        <h5 class="subtitle is-size-6">DESDE: {{ date_format($from, 'd/m/Y') }} HASTA: {{ date_format($to, 'd/m/Y') }}</h5>
    </center>
    <div class="columns has-margin-top-5">
        <div class="column is-12">
            <table class="table is-fullwidth">
                <tr>
                    <th><center><p class="is-size-6">FECHA DE IMPRESIÓN: {{ date('d/m/Y') }}</p></center></th>
                    <th><center><p class="is-size-6">HORA DE IMPRESIÓN: {{ date('h:i:s a') }}</p></center></th>
                </tr>
            </table>
        </div>
    </div>
    <div class="columns has-margin-top-0">
        <div class="column is-12">
            <table class="table is-bordered is-striped is-narrow is hoverable is-fullwidth">
                <thead>
                <tr>
                    <th class="is-size-7" style="width: 5%">DÍA</th>
                    <th class="is-size-7" style="width: 10%">T/D</th>
                    <th class="is-size-7" style="width: 20%">DOCUMENTO</th>
                    <th class="is-size-7" style="width: 45%">CLIENTE</th>
                    <th class="is-size-7" style="width: 10%">IGV 18%</th>
                    <th class="is-size-7" style="width: 10%">TOTAL</th>
                </tr>
                </thead>
                <thead>
                @foreach ($sales as $sale)
                    <tr>
                        <td class="is-size-7">{{ date_format($sale->created_at, 'd') }}</td>
                        <td class="is-size-7">{{ $sale->type }}</td>
                        <td class="is-size-7">{{ $sale->code }}</td>
                        <td class="is-size-7">{{ $sale->client_name }}</td>
                        <td class="is-size-7">{{ $sale->tax }}</td>
                        <td class="is-size-7">{{ $sale->total }}</td>
                    </tr>
                @endforeach
                </thead>
            </table>
        </div>
    </div>
@endsection

resources/views/pdf/product.blade.php
@extends('layouts.pdf')

@section('content')
    <center>
        <h2 class="title has-text-dark is-size-4">{{$title}}</h2>
        <h2 class="subtitle has-text-dark is-size-4">Sucursal: {{ Auth::user()->branch->name }}</h2>
    </center>
    <div class="columns has-margin-top-5">
        <div class="column is-12">
            <table class="table is-fullwidth">
                <tr>
                    <th><center class="is-size-6">FECHA DE IMPRESIÓN: {{ date('d/m/Y') }}</center></th>
                    <th><center class="is-size-6">HORA DE IMPRESIÓN: {{ date('h:i:s a') }}</center></th>
                </tr>
            </table>
        </div>
    </div>
    <div class="columns has-margin-top-0">
        <div class="column is-12">
            <table class="table is-bordered is-striped is-narrow is hoverable is-fullwidth">
                <thead>
                    <tr>
                        <th style="width: 15%">CÓDIGO</th>
                        <th style="width: 45%;">NOMBRE</th>
                        <th style="width: 20%">MARCA</th>
                        <th style="width: 10%">U.M</th>
                        <th style="width: 10%">STOCK</th>
                    </tr>
                </thead>
                <thead>
                    @foreach($products as $product)
                        <tr>
                            <td>{{ $product->code }}</td>
                            <td>{{ $product->name }}</td>
                            <td>{{ $product->brand }}</td>
                            <td>{{ $product->measure_unit }}</td>
                            <td>{{ $product->in_stock }}</td>
                        </tr>
                    @endforeach
                </thead>
            </table>
        </div>
    </div>
@endsection

resources/views/pdf/sellers.blade.php
@extends('layouts.pdf')

@section('content')
    <center>
        <h2 class="title has-text-dark is-size-4">{{$title}}</h2>
        <h5 class="subtitle is-size-6">Desde: 21/01/2019 Hasta: 12/12/2019</h5>
    </center>
    <div class="columns has-margin-top-5">
        <div class="column is-12">
            <table class="table is-fullwidth">
                <tr>
                    <th><center><p class="is-size-6">Fecha de impresión: 10/15/2019</p></center></th>
                    <th><center><p class="is-size-6">Hora de impresión: 10/15/2019</p></center></th>
                </tr>
            </table>
        </div>
    </div>
    <div class="columns has-margin-top-0">
        <div class="column is-12">
            <table class="table is-bordered is-striped is-narrow is hoverable is-fullwidth">
                <thead>
                <tr>
                    <th class="is-size-7" style="width: 40%">VENDEDOR</th>
                    <th class="is-size-7" style="width: 15%">Nº VENTAS</th>
                    <th class="is-size-7" style="width: 15%">MON. MIN. (S/)</th>
                    <th class="is-size-7" style="width: 15%">MON. MAX. (S/)</th>
                    <th class="is-size-7" style="width: 15%">MON. PROM. (S/)</th>
                </tr>
                </thead>
                <thead>
                <tr>
                    <td class="is-size-7">DENIS JOSELI SANCHEZ CARRANZA</td>
                    <td class="is-size-7">350</td>
                    <td class="is-size-7">15.50</td>
                    <td class="is-size-7">350.50</td>
                    <td class="is-size-7">150.50</td>
                </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection